### ISSUE TITLE
mex with intel oneAPI on maxOS M2

### ISSUE THREAD

**Issue by hjli1** [equipez/setup_mex#31]
(base) huijunli@office-Mac src % $MATLAB_ROOT/bin/mex xtimesy.F
使用 'Intel Fortran' 编译。
ld: warning: -undefined error is deprecated
ld: warning: -undefined error is deprecated
ld: warning: ignoring file '/private/var/folders/0d/dv0bsg010n570x9w4gdwhfcr0000gn/T/mex_10406043762116_26660/xtimesy.o': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/private/var/folders/0d/dv0bsg010n570x9w4gdwhfcr0000gn/T/mex_10406043762116_26660/fortran_mexapi_version.o': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/opt/intel/oneapi/compiler/2023.2.0/mac/compiler/lib/libifcore.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/opt/intel/oneapi/compiler/2023.2.0/mac/compiler/lib/libsvml.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/opt/intel/oneapi/compiler/2023.2.0/mac/compiler/lib/libimf.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/opt/intel/oneapi/compiler/2023.2.0/mac/compiler/lib/libintlc.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/opt/intel/oneapi/compiler/2023.2.0/mac/compiler/lib/libirc.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: Undefined symbols:
  _mexfunction_, referenced from:
      <initial-undefines>
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zaikunzhang** [comment]
Hi, thank you for your comment. Note the following from the readme. 

> Note that MATLAB requires you to install a supported (C or Fortran) compiler along with Xcode (on macOS) or Microsoft Visual Studio (on Windows). This package is not a hacking tool to circumvent these requirements, but a tool to help MATLAB recognize your compiler after these requirements are satisfied.

According to the documentation of MathWorks, on M2 you need nagfor to compile Fortran. If you don't have nagfor, there is no hope.

**Comment by hjli1** [comment]
but with the same M2, instead mixing it under MATLAB2022b (intel), no bug report:
... ...
使用 'Intel Fortran Composer XE' 编译。
/opt/intel/oneapi/compiler/2023.2.0/mac/bin/intel64/ifort -c -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD    -I"/Applications/MATLAB_R2022b.app/extern/include" -I"/Applications/MATLAB_R2022b.app/simulink/include" -fexceptions -fpp -mp1 -fp-model source -assume bscc -D__LP64__  -i8 -O2 "/Applications/MATLAB_R2022b.app/extern/examples/refbook/timestwo.F" -o /var/folders/0d/dv0bsg010n570x9w4gdwhfcr0000gn/T/mex_447730953195041_70959/timestwo.o
/opt/intel/oneapi/compiler/2023.2.0/mac/bin/intel64/ifort -c -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD    -I"/Applications/MATLAB_R2022b.app/extern/include" -I"/Applications/MATLAB_R2022b.app/simulink/include" -fexceptions -fpp -mp1 -fp-model source -assume bscc -D__LP64__  -i8 -O2 "/Applications/MATLAB_R2022b.app/extern/version/fortran_mexapi_version.F" -o /var/folders/0d/dv0bsg010n570x9w4gdwhfcr0000gn/T/mex_447730953195041_70959/fortran_mexapi_version.o
/usr/bin/xcrun -sdk macosx14.2 clang -Wl,-twolevel_namespace -undefined error -mmacosx-version-min=10.15 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -Wl,-exported_symbols_list,"/Applications/MATLAB_R2022b.app/extern/lib/maci64/fortran_exportsmexfileversion.map" -bundle -O /var/folders/0d/dv0bsg010n570x9w4gdwhfcr0000gn/T/mex_447730953195041_70959/timestwo.o /var/folders/0d/dv0bsg010n570x9w4gdwhfcr0000gn/T/mex_447730953195041_70959/fortran_mexapi_version.o   -L"/Applications/MATLAB_R2022b.app/bin/maci64" -lmx -lmex -lmat -L"/opt/intel/oneapi/compiler/2023.2.0/mac/compiler/lib" -lifcore -limf -lintlc -lirc -lsvml -o timestwo.mexmaci64
ld: warning: -undefined error is deprecated
ld: warning: -undefined error is deprecated
ld: warning: no platform load command found in '/private/var/folders/0d/dv0bsg010n570x9w4gdwhfcr0000gn/T/mex_447730953195041_70959/timestwo.o', assuming: macOS
ld: warning: no platform load command found in '/private/var/folders/0d/dv0bsg010n570x9w4gdwhfcr0000gn/T/mex_447730953195041_70959/fortran_mexapi_version.o', assuming: macOS

xcrun install_name_tool -change libifcore.dylib @rpath/libifcore.dylib timestwo.mexmaci64
xcrun install_name_tool -change libimf.dylib @rpath/libimf.dylib timestwo.mexmaci64
xcrun install_name_tool -change libintlc.dylib @rpath/libintlc.dylib timestwo.mexmaci64
xcrun install_name_tool -change libirc.dylib @rpath/libirc.dylib timestwo.mexmaci64
xcrun install_name_tool -change libsvml.dylib @rpath/libsvml.dylib timestwo.mexmaci64
MEX 已成功完成。

**Comment by zaikunzhang** [comment]
> but with the same M2, instead of using MATLAB2024a (arm64), we mex it under MATLAB2022b (intel64), yet, no bug report:

This is because MATLAB R2022b does not really use the M2 chip as an M2 chip; instead, it emulates an Intel chip. Check MathWorks documentation. Thanks.
